server:
  port: 8080
  max-http-header-size: 102400
# 百度人脸api
baidu:
  app_id: 24601725
  api_key: T5UmqfT0mPnlBmbncvDPnDDz
  secret_key: sU7rhCZYrzNYan2UpbEjYEsxPrNDXDT2
# 开启swagger
swagger:
  enable: true
# 数据库及jpa
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/face_sign_in?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: face_sign_in
    password: 123456
    hikari:
      max-lifetime: 50000
      maximum-pool-size: 10
      minimum-idle: 3
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    database: 0 # Redis数拙库索引(默认为0 )
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码 (默认为空)
    jedis:
      pool:
        max-active: 8 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1ms #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idLe: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000ms
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      accept_empty_string_as_null_object: true
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760

erupt-app:
  # 登录失败几次出现验证码，值为0时表示一直需要登录验证码
  verifyCodeCount: 2
  # 登录密码是否加密传输，特殊场景如：LDAP登录可关闭该功能获取密码明文
  pwdTransferEncrypt: true
erupt:
  # 是否开启csrf防御
  csrfInspect: true
  # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 Spring Boot）
  redisSession: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  uploadPath: D:/erupt/pictures
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 登录session时长（redisSession为true时有效）
  upms.expireTimeByLogin: 60
  # 是否开启任务调度（导入erupt-job时有效）
  job.enable: true
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true

